const ERROR_CODE = {
  ErrSuccess: 0,
  ErrInternalError: 1,
  ErrInvalidParam: 2,
  ErrDBDataNotReady: 3,
  ErrUserNotFound: 4,
  ErrDataNotFound: 5,
  ErrClinicNotFound: 6,
  ErrDeptNotFound: 7,
  ErrPasswordNotMatch: 8,
  ErrUserExpired: 9,
  ErrUserAnotherPlaceLogined: 10,
  ErrUserNeedRelogin: 11,
  ErrSessionNotMatch: 12,
  ErrGetSmsCodeFailed: 13,
  ErrSmsCodeIncorrect: 14,
  ErrGetSmsCodeTooFast: 15,
  ErrUserNotSetPhone: 16,
  ErrUserPhoneNotMatched: 17,
  ErrPhoneRegisteredByOthers: 18,
  ErrDbOperationError: 19,
  ErrUserIsDiabled: 20,
  ErrUserNoPermission: 21,
  ErrUsersLimitExceeded: 22,
  ErrPermissionShouldLessThanParent: 23,
  ErrPatientNotFind: 24,
  ErrPatientPhoneOccupied: 25,
  ErrRegistrationNotFind: 26,
  ErrOutpatientChargeNotFind: 27,
  ErrOutpatientChargeStatus: 28,
};

export default ERROR_CODE;